### ISSUE TITLE
About us page

### ISSUE THREAD

**Issue by Princesso** [oscafrica/oscafrica.org#11]
https://www.figma.com/file/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=1087%3A2503

**Comment by agbanusi** [comment]
Hi, is there a design and content I could use in making this? I'd love to do this please.

**Comment by perriefidelis** [comment]
See designs in

-  Desktop in [design issue #22](https://github.com/oscafrica/Design/issues/22) 
-  Tablet in [design issues #23](https://github.com/oscafrica/Design/issues/23)
- Mobile in [design issues #24 ](https://github.com/oscafrica/Design/issues/24)

**Comment by laviedegeorge** [comment]
hi! i would love to be assigned to this issue if it is free @Princesso @perriefidelis

**Comment by Princesso** [comment]
Feel free to do so

**Comment by laviedegeorge** [comment]
@Princesso i am not allowed to assign the issue to myself. I guess it's because i am not at least a member of the organization.

**Comment by Princesso** [comment]
You could just work on it and send in a PR.

**Comment by laviedegeorge** [comment]
Ok thanks, I am on it.
