### ISSUE TITLE
Redesign footer component

### ISSUE THREAD

**Issue by Princesso** [oscafrica/oscafrica.org#12]

**Comment by noelukwa** [comment]
Hello, is there a mockup in place already that i have to follow in redesigning the footer or anything goes.

**Comment by Princesso** [comment]
There is a mockup in place @alusicode .
You can have an insight to the OSCA designs here: https://github.com/oscafrica/Design
You can also explore designs specific to this project [here:](https://www.figma.com/proto/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=167%3A327&viewport=273%2C738%2C0.1726166009902954&scaling=min-zoom)

Do let me know if you have more questions.

**Comment by perriefidelis** [comment]
Here are more specific designs

[Desktop](https://www.figma.com/file/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=616%3A325)
Tablet ([834px](https://www.figma.com/file/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=616%3A325), [768px](https://www.figma.com/file/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=616%3A325))
[Mobile](https://www.figma.com/file/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=616%3A325)

Full [style guide](https://www.figma.com/file/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=608%3A0)

**Comment by laviedegeorge** [comment]
Hi @alusicode  are you till working on this issue?

**Comment by noelukwa** [comment]
yes. almost done

**Comment by laviedegeorge** [comment]
ok.

**Comment by laviedegeorge** [comment]
@alusicode  the issue wasn't assigned to anyone, that's why i asked.

**Comment by Princesso** [comment]
Could you please assign the issue to yourself when you start working on any? @alusicode

**Comment by laviedegeorge** [comment]
hi @Princesso  please is there an official way of communication for this project? like a slack channel or Discord. i have questions i need to ask.

**Comment by Princesso** [comment]
There is a discord channel. cc: @samswag or @perriefidelis could you please share a link to the discord channel?

**Comment by samswag** [comment]
Sure, @laviedegeorge you can jump on the #engineering channel via [Discord](https://discord.gg/KBJPVC), make sure you use #general to introduce yourself and feel free to join other channels.

**Comment by laviedegeorge** [comment]
@samswag thanks! I am on the discord server already. I will head to engineering...

**Comment by Cirediallo** [comment]
Hi did the design changed ? I wanted to start working on an issue but I don't see the problem and it seems like it's not the same design no more. thank for hightlingting me
