### ISSUE TITLE
Blank space below the Footer

### ISSUE THREAD

**Issue by Pariola-droid** [oscafrica/oscafrica.org#20]
![osca](https://user-images.githubusercontent.com/58291503/92460875-693f6a80-f1c0-11ea-9d46-3c31e7fc6f7c.png)

On large screens 
there's a little bit of problem-related to the page size, the footer.

The white blank space below the footer. 

i tried it out on a bigger screen, it was way bigger than the sample i sent(screen capture)

**Comment by Cirediallo** [comment]
Gonna go to fix this one

**Comment by Mancancode** [comment]
has this issue been fixed?

**Comment by Cirediallo** [comment]
I don't know seems like the design has changed so waiting for the core team to confirm or not
