### ISSUE TITLE
Issue: Build new button variation

### ISSUE THREAD

**Issue by laviedegeorge** [oscafrica/oscafrica.org#26]
Hi! There is a new button variation in the design of the new Osca website and it has not been built and added to the button component as a new variation. Check the "our-community" section in the about-us page design to see a sample of this button variation.

**Comment by laviedegeorge** [comment]
I am currently working on the about-us #11 and have built this button. I would love to add it to the button component as a variation and add it to Storybook too. @Princesso @alabobriggs

**Comment by Princesso** [comment]
I think this can also be achieved by passing the right props to buttons.

**Comment by Princesso** [comment]
Do let me know if you need help getting this done, we can jump on a call.

**Comment by laviedegeorge** [comment]
Hi! if you are available now I would prefer a call so I can understand better. Although I tried adding styles, the hover wouldn't work properly.

**Comment by joshtom** [comment]
Hi @laviedegeorge Have you been able to achieve this?

**Comment by laviedegeorge** [comment]
i have, but have not gotten confirmation from @Princesso

**Comment by joshtom** [comment]
Okay. Noted
