### ISSUE TITLE
Issue: Gotham font missing

### ISSUE THREAD

**Issue by laviedegeorge** [oscafrica/oscafrica.org#27]
The Gotham font should be used on some write-ups in this design but it is missing in the fonts folder and Tailwind configuration file.

**Comment by dpkreativ** [comment]
Can I work on this please?

**Comment by laviedegeorge** [comment]
@Princesso @alabobriggs

**Comment by Princesso** [comment]
You can @laviedegeorge or @dpkreativ

**Comment by laviedegeorge** [comment]
@dpkreativ you can work on it. @Princesso thanks!

**Comment by dpkreativ** [comment]
thanks... I'll get started

**Comment by dpkreativ** [comment]
@Princesso I just made a pull request... kindly check. Thanks
