### ISSUE TITLE
OSCA Home Page

### ISSUE THREAD

**Issue by Princesso** [oscafrica/oscafrica.org#8]
The design for the home page can be found [here](https://www.figma.com/proto/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=167%3A186&viewport=273%2C738%2C0.1726166009902954&scaling=min-zoom): 

Concerns:
@perriefidelis I noticed that images on page one and page two on the community section on the home page are different. Is the section intended to have carousel images?

**Comment by perriefidelis** [comment]
Ohh let me check that

**Comment by perriefidelis** [comment]
> The design for the home page can be found [here](https://www.figma.com/proto/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=167%3A186&viewport=273%2C738%2C0.1726166009902954&scaling=min-zoom):
> 
> Concerns:
> @perriefidelis I noticed that images on page one and page two on the community section on the home page are different. Is the section intended to have carousel images?

@Princesso fixed, the images are in sync now 🚀

**Comment by alabobriggs** [comment]
@BolajiAyodeji @Princesso  I was thinking of breaking down this page into tiny sections so we can include more contributors. What do you think?

**Comment by Princesso** [comment]
> @BolajiAyodeji @Princesso I was thinking of breaking down this page into tiny sections so we can include more contributors. What do you think?

Let's just work on this, at the moment we do not have the capacity to push for community contributions

**Comment by bemijonathan** [comment]
Hi everyone i'd love to help out.. how do i get involved

**Comment by Princesso** [comment]
> Hi everyone i'd love to help out.. how do i get involved

Hello @bemijonathan, thanks for reaching out. You could start out by having a look at the readme file for the project. Also, you are free to pick any of the issues that is currently not assigned to anyone and start working on it.

The framework is gatsby. If you understand react, you should be able to start contributing immediately. If you don't, I would suggest that you spend some hours trying on its basics.

We're always here to help so reach out to any of the contributors to gain more clarity if you need more information. Thank you. 😊

**Comment by bemijonathan** [comment]
Is there a group where I can talk with designers or someone in the design group I have an issue trying to export some images

**Comment by Princesso** [comment]
@perriefidelis could you please help @bemijonathan .

@bemijonathan Perrie is in charge of the design team

**Comment by perriefidelis** [comment]
Yeah sure. @bemijonathan, what issues?

**Comment by bemijonathan** [comment]
I will send you a message on twitter I need the clear images for the home page the ones I exported are a bit blurry/faded

**Comment by perriefidelis** [comment]
Alright cool ... maybe I can create a google drive that contains all the images? Will that help?

**Comment by bemijonathan** [comment]
Yes, That will be perfect

**Comment by perriefidelis** [comment]
@bemijonathan here is the [drive ](https://drive.google.com/drive/folders/1O63X8OV1YGgEss7T4svQxPrwWqC0InoS?usp=sharing) or [GitHub](https://github.com/oscafrica/Design/tree/master/Brand%20Assets/OSCA%20website%20images)

**Comment by perriefidelis** [comment]
See design screens for homepage;

- Desktop in [design issue #3](https://github.com/oscafrica/Design/issues/3)
- Tablet in [design issue #23](https://github.com/oscafrica/Design/issues/23)
- Mobile in [design issue #7](https://github.com/oscafrica/Design/issues/7)

**Comment by bemijonathan** [comment]
ok noted
