### ISSUE TITLE
Redesign header component

### ISSUE THREAD

**Issue by Princesso** [oscafrica/oscafrica.org#9]
The header on the design looks different from what is currently on the page. 

Redesign header to look like the one in the [design](https://www.figma.com/proto/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=167%3A186&viewport=273%2C738%2C0.1726166009902954&scaling=min-zoom).

**Comment by perriefidelis** [comment]
[Desktop](https://www.figma.com/file/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=616%3A325)
Tablet ([834px](https://www.figma.com/file/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=616%3A325), [768px](https://www.figma.com/file/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=616%3A325))
[Mobile](https://www.figma.com/file/dDQ0f43gracsqn1LJYk91E/New-OSCA-website?node-id=616%3A325)

**Comment by joshtom** [comment]
This issue is still open, Can I still work on it?

**Comment by Princesso** [comment]
Feel free to work on it. Expecting a pull request from you !!!

**Comment by joshtom** [comment]
> Feel free to work on it. Expecting a pull request from you !!!

Is there a link to the design to follow?

**Comment by Princesso** [comment]
Kindly check the comments on this issue. Peace has dropped a link to designs @joshtom

**Comment by joshtom** [comment]
> Kindly check the comments on this issue. Peace has dropped a link to designs @joshtom

Great. Will check it out.

**Comment by AbdQaadir** [comment]
Hi, @Princesso can I work on this?

**Comment by AbdQaadir** [comment]
And is what is meant by the header component is the navigation bar?
